version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://birgilisezerenis2705:2dv41SbpHP8VH4Gz@cluster0.ty3o7nb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - SPRING_DATA_MONGODB_DATABASE=recipegallery
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: